version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
      # docker:
      #   - image: circleci/python:rc-browsers
    executor: python/default
    steps:
      - checkout

      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - run: ls
      # - run:
      #     command: sudo pip install pipenv && pipenv install
      - run: 
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update  && sudo apt-get install google-chrome-stable
          name: Install Google Chrome

      - run:
          command: behave 
          name: Behave tests

workflows:
  main:
    jobs:
      - build
