version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout

      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - run: ls
      # - run:
      #     command: sudo pip install pipenv && pipenv install
      - run:
          command: behave 
          name: Behave tests

workflows:
  main:
    jobs:
      - build
