version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    docker:
      - image: circleci/python:rc-browsers
    executor: python/default
    steps:
      - checkout
      # - python/install-packages:
      #     pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
          pypi-cache: false
      # - python/install-packages:
      #     args: behave
      #     pkg-manager: pip
          # pypi-cache: false
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      - run: ls
      # - run:
      #     command: sudo pip install pipenv && pipenv install
      # - run:
      #     command: behave 
      #     name: Behave tests

workflows:
  main:
    jobs:
      - build
